server.port=8080
spring.application.name=Tower Defense API

# NEON DATABASE
spring.datasource.url=jdbc:postgresql://ep-divine-wave-aoxvg59c.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_edOcV4Pt7gXu
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.root=WARN
logging.level.com.towergame=INFO